# Generated by Django 3.2.9 on 2021-11-25 16:55

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('activation_date', models.DateTimeField(auto_now_add=True)),
                ('deactivation_date', models.DateTimeField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='status_lookup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('activation_date', models.DateTimeField(auto_now_add=True)),
                ('deactivation_date', models.DateTimeField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='user_type_lookup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('activation_date', models.DateTimeField(auto_now_add=True)),
                ('deactivation_date', models.DateTimeField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.TextField()),
                ('lname', models.TextField()),
                ('address', models.TextField()),
                ('url', models.FilePathField(path=core.models.images_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('activation_date', models.DateTimeField(auto_now_add=True)),
                ('deactivation_date', models.DateTimeField(blank=True, default=None)),
                ('user_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user_type_lookup')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('img_url', models.FilePathField(blank=True, path=core.models.images_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('activation_date', models.DateTimeField(auto_now_add=True)),
                ('deactivation_date', models.DateTimeField(blank=True, default=None)),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.status_lookup')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('activation_date', models.DateTimeField(auto_now_add=True)),
                ('deactivation_date', models.DateTimeField(blank=True, default=None)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='item_image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.FilePathField(path=core.models.images_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('activation_date', models.DateTimeField(auto_now_add=True)),
                ('deactivation_date', models.DateTimeField(blank=True, default=None)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
