# Generated by Django 3.2.9 on 2021-11-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_image',
            name='url',
            field=models.FilePathField(path='static/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.FilePathField(blank=True, path='static/images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.FilePathField(path='static/images/'),
        ),
    ]
