# Generated by Django 3.2.9 on 2021-11-25 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211125_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.product'),
        ),
        migrations.AlterField(
            model_name='item_image',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='core.status_lookup'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_types', to='core.user_type_lookup'),
        ),
    ]
