# Generated by Django 3.2.9 on 2021-11-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211125_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='url',
        ),
        migrations.AddField(
            model_name='user',
            name='img_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='item_image',
            name='url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='status_lookup',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='fname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='lname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user_type_lookup',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
