# Generated by Django 3.2.9 on 2021-11-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211126_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.TextField(default='coming soon'),
            preserve_default=False,
        ),
    ]
