# Generated by Django 3.2.9 on 2021-11-27 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_item_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='core_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_no', models.IntegerField()),
                ('address', models.TextField()),
                ('img_url', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('activation_date', models.DateTimeField(auto_now_add=True)),
                ('deactivation_date', models.DateTimeField(blank=True, default=None)),
                ('core_user_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_types', to='core.user_type_lookup')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.core_user'),
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
