# Generated by Django 3.2.9 on 2021-11-27 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211127_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='core_user',
            name='mobile_no',
        ),
        migrations.AddField(
            model_name='core_user',
            name='phone_no',
            field=models.IntegerField(default=1234567890, validators=[django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
