# Generated by Django 3.2.9 on 2021-11-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_core_user_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core_user',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
